export const items = [
  { key: 1, name: 'Ahmad Fauzan', class: 'VII.1', checkInTime: '07:15:00', status: 'On Time' },
  { key: 2, name: 'Aisyah Zahra', class: 'VII.1', checkInTime: '07:16:00', status: 'On Time' },
  { key: 3, name: 'Budi Santoso', class: 'VII.2', checkInTime: '07:17:00', status: 'Terlambat' },
  { key: 4, name: 'Citra Dewi', class: 'VII.2', checkInTime: '07:18:00', status: 'On Time' },
  { key: 5, name: 'Dewi Anjani', class: 'VII.3', checkInTime: '07:19:00', status: 'On Time' },
  { key: 6, name: 'Eka Pratama', class: 'VII.3', checkInTime: '07:20:00', status: 'Terlambat' },
  { key: 7, name: 'Farhan Malik', class: 'VII.4', checkInTime: '07:21:00', status: 'On Time' },
  { key: 8, name: 'Gita Nurani', class: 'VII.4', checkInTime: '07:22:00', status: 'On Time' },
  { key: 9, name: 'Hadi Firmansyah', class: 'VII.5', checkInTime: '07:23:00', status: 'Terlambat' },
  { key: 10, name: 'Indah Lestari', class: 'VII.5', checkInTime: '07:24:00', status: 'On Time' },
  { key: 11, name: 'Joko Susanto', class: 'VII.6', checkInTime: '07:25:00', status: 'Terlambat' },
  { key: 12, name: 'Kartini Sri', class: 'VII.6', checkInTime: '07:26:00', status: 'On Time' },
  { key: 13, name: 'Lina Marlina', class: 'VII.7', checkInTime: '07:27:00', status: 'Terlambat' },
  { key: 14, name: 'Miko Darmawan', class: 'VII.7', checkInTime: '07:28:00', status: 'On Time' },
  { key: 15, name: 'Nisa Anggraini', class: 'VII.8', checkInTime: '07:29:00', status: 'On Time' },
  { key: 16, name: 'Omar Khayyam', class: 'VII.8', checkInTime: '07:30:00', status: 'Terlambat' },
  { key: 17, name: 'Putri Salsabila', class: 'VII.9', checkInTime: '07:31:00', status: 'On Time' },
  { key: 18, name: 'Qori Hakim', class: 'VII.9', checkInTime: '07:32:00', status: 'Terlambat' },
  { key: 19, name: 'Rama Wijaya', class: 'VIII.1', checkInTime: '07:33:00', status: 'On Time' },
  { key: 20, name: 'Sinta Dewi', class: 'VIII.1', checkInTime: '07:34:00', status: 'On Time' },
  { key: 21, name: 'Tono Saputra', class: 'VIII.2', checkInTime: '07:35:00', status: 'Terlambat' },
  { key: 22, name: 'Umi Suryani', class: 'VIII.2', checkInTime: '07:36:00', status: 'On Time' },
  { key: 23, name: 'Vina Lestari', class: 'VIII.3', checkInTime: '07:37:00', status: 'On Time' },
  {
    key: 24,
    name: 'Wawan Iskandar',
    class: 'VIII.3',
    checkInTime: '07:38:00',
    status: 'Terlambat',
  },
  { key: 25, name: 'Xenia Marlina', class: 'VIII.4', checkInTime: '07:39:00', status: 'On Time' },
  { key: 26, name: 'Yusuf Pratama', class: 'VIII.4', checkInTime: '07:40:00', status: 'Terlambat' },
  { key: 27, name: 'Zahra Annisa', class: 'VIII.5', checkInTime: '07:41:00', status: 'On Time' },
  { key: 28, name: 'Agus Prasetyo', class: 'VIII.5', checkInTime: '07:42:00', status: 'Terlambat' },
  { key: 29, name: 'Bagas Saputra', class: 'VIII.6', checkInTime: '07:43:00', status: 'On Time' },
  { key: 30, name: 'Cahya Putri', class: 'VIII.6', checkInTime: '07:44:00', status: 'On Time' },
  { key: 31, name: 'Dedi Susilo', class: 'VIII.7', checkInTime: '07:45:00', status: 'Terlambat' },
  { key: 32, name: 'Elisa Nur', class: 'VIII.7', checkInTime: '07:46:00', status: 'On Time' },
  { key: 33, name: 'Faisal Ridwan', class: 'VIII.8', checkInTime: '07:47:00', status: 'On Time' },
  { key: 34, name: 'Gilang Arya', class: 'VIII.8', checkInTime: '07:48:00', status: 'Terlambat' },
  { key: 35, name: 'Hafiz Nur', class: 'VIII.9', checkInTime: '07:49:00', status: 'On Time' },
  { key: 36, name: 'Indira Anjani', class: 'VIII.9', checkInTime: '07:50:00', status: 'Terlambat' },
  { key: 37, name: 'Jaka Rahman', class: 'IX.1', checkInTime: '07:51:00', status: 'On Time' },
  { key: 38, name: 'Kirana Safitri', class: 'IX.1', checkInTime: '07:52:00', status: 'On Time' },
  { key: 39, name: 'Lutfi Suryono', class: 'IX.2', checkInTime: '07:53:00', status: 'Terlambat' },
  { key: 40, name: 'Maya Sari', class: 'IX.2', checkInTime: '07:54:00', status: 'On Time' },
  // Tambahkan pola yang sama hingga 100 data
];
